### PR TITLE
Emre us8

### PR DESCRIPTION
**Pull request by emcemen**
I completed user story-8 guys if you have any time for check that should be fine for me. Thank you

### CODE REVIEW

**Comment by sabiyevkairat** [comment]
Hi Emre! Great work! I see you added sleep commands in several places. Does it not work without them? Thanks

**Comment by emcemen** [comment]
Thanks Kai, you are right about it. I know it's not a proper way to use waits in the code I was just wondering the code is working well or not. I forgot them in there yeah it is working without waits too. we  can  delete  all waits ( sleeps) codes. Thank you.

**Comment by sabiyevkairat** [comment]
I was just curious :)

**Review by Zoubair-R — APPROVED** [review]
looks good.

**Pull request closed without merging**
