### PR TITLE
Zoubair us9

### PR DESCRIPTION
**Pull request by Zoubair-R**

### CODE REVIEW

**Review by DenizCaprak — CHANGES_REQUESTED** [review]
Hey Zoubair. You need to merge to dev instead of master. Also on runner class change the dryrun to false and remove your tag name. I couln't look at the in depth becaseu my head is spinning, When you fix them and recreate a pull request also add everyone else as a rewiewer. This way they can check something i might miss.

**Comment by Zoubair-R** [comment]
Hi Deniz,

Thank you! I will make the changes.
I hope you feel better.

Zoubair Rhomid

**Review by sabiyevkairat — CHANGES_REQUESTED** [review]
Hi Zoubair,

Thanks for your hard work! A few things:

1. Please make sure to work on your step_def file rather than someone else's. In this particular merge, I see code added to Login_StepDefinition and nothing in US9_StepDefinitions.
2. No need to create another login page (US9_LoginPage). Please use the already developed Login Page
3. Please rename your page and step_definition to something more meaningful rather than US9. Your user story is about comments, so you can include that in the name
4. No need to change anything in login.feature

Thanks
Kai

**Comment by Zoubair-R** [comment]
The requested changes were made, work in progress for  Comments_StepDefinitions.

**Comment by Zoubair-R** [comment]
The requested changes were made, work in progress for Comments_StepDefinitions.

**Pull request closed without merging**
